package game

SCREEN_WIDTH :: 640 // px
SCREEN_HEIGHT :: 360 // px

BG_LAYERS :: 3 

MUSIC_VOLUME :: 0.2 // multiplier [0..1]
SFX_VOLUME :: 0.6 // multiplier [0..1]

GAMEPAD_ID :: 0 
STICK_DEADZONE :: 0.2 // [0..1]

PLAYER_SPEED :: 95.0 // px/s
PLAYER_MAX_HP :: 125 // hp
PLAYER_HIT_DAMAGE :: 3 // hp/hit
PLAYER_HIT_RADIUS :: 4.0 // px
PLAYER_INVULN_TIME :: 0.6 // s
PLAYER_FLASH_HZ :: 10.0 // toggles/s
PLAYER_ANIM_FPS :: 8.0 // frames/s
PLAYER_FRAME_W :: 8 // px
PLAYER_FRAME_H :: 8 // px
PLAYER_IDLE_FRAMES :: 7 
PLAYER_MOVE_FRAMES :: 3 
PLAYER_DRAW_SCALE :: 2 // multiplier
RETICLE_FRAME_W :: 8 // px
RETICLE_FRAME_H :: 8 // px
RETICLE_DISTANCE :: 90.0 // px

PLAYER_PROJECTILE_ORIGIN_Y_OFFSET :: -3.0 // px

PLAYER_DASH_SPEED :: 480.0 // px/s
PLAYER_DASH_DURATION :: 0.18 // s
PLAYER_DASH_COOLDOWN :: 0.45 // s
PLAYER_DASH_TRAIL_LEN :: 12 
PLAYER_DASH_TRAIL_FADE_TIME :: 0.35 // s
PLAYER_DASH_TRAIL_MAX_ALPHA :: 0.65 // multiplier

PLAYER_MAX_STAMINA :: 50.0 // stamina
PLAYER_DASH_STAMINA_COST :: 5.0 // stamina/dash
PLAYER_STAMINA_RECOVER_RATE :: 2.0 // stamina/s
DASH_FRENZY_EXTRA_STAMINA_COST :: 2.0 // stamina/dash
HEART_OF_STEEL_RECOVER_MULT :: 1.3 // multiplier (unitless)

SLOW_TIME_FACTOR :: 0.5 // multiplier
SLOW_TIME_STAMINA_PER_SEC :: 10.0 // stamina/s
SLOW_TIME_TINT_R :: 80 // [0..255]
SLOW_TIME_TINT_G :: 180 // [0..255]
SLOW_TIME_TINT_B :: 255 // [0..255]
SLOW_TIME_TINT_ALPHA_BASE :: 55 // alpha [0..255]
SLOW_TIME_TINT_ALPHA_PULSE :: 20 // alpha [0..255]
SLOW_TIME_PULSE_HZ :: 1.6 // Hz
SLOW_TIME_LPF_CUTOFF_HZ :: 170.0 // Hz

ENEMY_COUNT :: 6 
GRUNT_WAVE_COUNT :: 3 
ENEMY_FRAME_W :: 16 // px
ENEMY_FRAME_H :: 16 // px
ENEMY_FRAMES :: 2 
ENEMY_ANIM_FPS :: 8.0 // frames/s
ENEMY_DRAW_SCALE :: 2 // multiplier
ENEMY_ORBIT_RADIUS :: 120.0 // px
ENEMY_SPAWN_RADIUS :: 500.0 // px
ENEMY_APPROACH_SPEED :: 200.0 // px/s
ENEMY_ORBIT_SPEED :: 0.6 // rad/s
ENEMY_FIRE_INTERVAL :: 3.0 // s
ENEMY_WAVE_BOOST_THRESHOLD :: 3 
ENEMY_FIRE_FREQ_BOOST :: 0.5 // fraction
ENEMY_BULLETS_PER_BURST :: 12 
ENEMY_BULLET_SPEED :: 70.0 // px/s
ENEMY_MAX_HP :: 21 // hp
ENEMY_HIT_RADIUS :: 10.0 // px
ENEMY_HIT_FLASH_TIME :: 0.08 // s

WEIRDGUY_WAVE_COUNT :: 6 
WEIRDGUY_MAX_HP :: 4 // hp
WEIRDGUY_FRAME_W :: 16 // px
WEIRDGUY_FRAME_H :: 16 // px
WEIRDGUY_FRAMES :: 1 
WEIRDGUY_DRAW_SCALE :: 2 // multiplier
WEIRDGUY_HIT_RADIUS :: 10.0 // px
WEIRDGUY_PATROL_RANGE :: 220.0 // px
WEIRDGUY_SPEED :: 280.0 // px/s
WEIRDGUY_Y_MIN :: 30.0 // px
WEIRDGUY_Y_MAX :: 200.0 // px
WEIRDGUY_FIRE_INTERVAL :: 0.08 // s
WEIRDGUY_BULLET_SPEED :: 100.0 // px/s
WEIRDGUY_DEATH_FRAMES :: 6
WEIRDGUY_DEATH_FRAME_DUR :: 0.07 // s
WEIRDGUY_CORPSE_MAX :: 16

BOSS_TRIGGER_WAVE :: 4 
BOSS_MAX_HP :: 110 // hp
BOSS_FRAME_W :: 32 // px
BOSS_FRAME_H :: 32 // px
BOSS_FRAMES :: 5
BOSS_DEATH_FRAMES :: 7
BOSS_DEATH_FRAME_DUR :: 0.2 // s
BOSS_DRAW_SCALE :: 2 // multiplier
BOSS_ANIM_FPS :: 6.0 // frames/s
BOSS_HIT_RADIUS :: 16.0 // px
BOSS_HIT_FLASH_TIME :: 0.08 // s
BOSS_SPAWN_X :: 320.0 // px
BOSS_SPAWN_Y :: 60.0 // px
BOSS_SWAY_AMPLITUDE :: 38.0 // px
BOSS_SWAY_FREQ :: 0.8 // Hz
BOSS_FIGURE8_Y_RATIO :: 0.5 // multiplier
BOSS_FIRE_INTERVAL :: 0.033 // s
BOSS_BULLET_ROWS :: 6 
BOSS_ANGLE_INCREMENT_DEG :: 5.0 // deg/burst
BOSS_BULLET_SPEED :: 130.0 // px/s
BOSS_SNEAK_SPAWN_INTERVAL :: 4.0 // s
BOSS_NAME :: "GOLGATHA" 
BOSS_NAME_FONT_SIZE :: 12 // px
BOSS_HUD_BAR_W :: 360 // px
BOSS_HUD_BAR_H :: 8 // px
BOSS_HUD_NAME_Y :: 6 // px
BOSS_HUD_BAR_Y :: 22 // px

MORGAN_CHATTER_INTERVAL_MIN :: 4.0 // s
MORGAN_CHATTER_INTERVAL_MAX :: 8.0 // s

MORGAN_NAME :: "MORGAN"
MORGAN_FRAME_W :: 32 // px
MORGAN_FRAME_H :: 32 // px
MORGAN_IDLE_FRAMES :: 9
MORGAN_DEATH_FRAMES :: 13
MORGAN_DEATH_FRAME_DUR :: 0.2 // s
MORGAN_DRAW_SCALE :: 2 // multiplier
MORGAN_ANIM_FPS :: 8.0 // frames/s
MORGAN_HIT_RADIUS :: 40.0 // px
MORGAN_PHASE_HP :: 300 // hp
MORGAN_PHASE_TRANSITION_DUR :: 1.5 // s
MORGAN_SHIELD_HP :: 50 // hp
MORGAN_SHIELD_RECOVER_TIME :: 5.0 // s
MORGAN_SPAWN_X :: 320.0 // px
MORGAN_SPAWN_Y :: 70.0 // px
MORGAN_P1_SWAY_AMP :: 100.0 // px
MORGAN_P1_SWAY_FREQ :: 0.24 // Hz
MORGAN_P2_SWAY_AMP :: 110.0 // px
MORGAN_P2_SWAY_FREQ :: 0.48 // Hz
MORGAN_P3_SWAY_AMP :: 140.0 // px
MORGAN_P3_SWAY_FREQ :: 0.57 // Hz
MORGAN_P1_FIRE_INTERVAL :: 0.18 // s
MORGAN_P1_ROWS :: 3 
MORGAN_P1_ANGLE_INC_DEG :: 11.0 // deg/burst
MORGAN_P1_BULLET_SPEED :: 65.0 // px/s
MORGAN_P2_FIRE_INTERVAL :: 0.1 // s
MORGAN_P2_ROWS :: 5 
MORGAN_P2_ANGLE_INC_DEG :: 7.0 // deg/burst
MORGAN_P2_BULLET_SPEED :: 95.0 // px/s
MORGAN_P3_FIRE_INTERVAL :: 0.08 // s
MORGAN_P3_ROWS :: 7 
MORGAN_P3_ANGLE_INC_DEG :: 5.0 // deg/burst
MORGAN_P3_BULLET_SPEED :: 120.0 // px/s
MORGAN_ORB_INTERVAL :: 3.5 // s
MORGAN_ORB_SPEED :: 38.0 // px/s
MORGAN_ORB_LIFE :: 4.5 // s
MORGAN_ORB_HIT_RADIUS :: 8.0 // px
MORGAN_ORB_DRAW_RADIUS :: 11.0 // px
MORGAN_ORB_BURST_COUNT :: 18 
MORGAN_ORB_BURST_SPEED :: 80.0 // px/s
MORGAN_P2_SNEAK_INTERVAL :: 3.5 // s

SNEAK_MAX :: 6 
LEVEL1_SNEAK_CAP :: 2 
SNEAK_SPAWN_CHANCE :: 0.5 // probability [0..1]
SNEAK_FRAME_W :: 16 // px
SNEAK_FRAME_H :: 16 // px
SNEAK_FRAMES :: 1 
SNEAK_DRAW_SCALE :: 2 // multiplier
SNEAK_SPAWN_MARGIN :: 24.0 // px
SNEAK_SWAY_AMPLITUDE :: 14.0 // px
SNEAK_SWAY_FREQ :: 1.4 // Hz
SNEAK_BURST_INTERVAL :: 0.3333 // s
SNEAK_BULLETS_PER_BURST :: 4 
SNEAK_BURST_FAN_DEG :: 24.0 // deg
SNEAK_BULLET_SPEED :: 90.0 // px/s
SNEAK_TELEPORT_INTERVAL :: 10.0 // s
SNEAK_MAX_HP :: 6 // hp
SNEAK_HIT_RADIUS :: 7.0 // px
SNEAK_HIT_FLASH_TIME :: 0.08 // s

CYCLOPS_MAX_HP :: 50 // hp
CYCLOPS_FRAME_W :: 16 // px
CYCLOPS_FRAME_H :: 16 // px
CYCLOPS_FRAMES :: 9 
CYCLOPS_ANIM_FPS :: 8.0 // frames/s
CYCLOPS_DRAW_SCALE :: 2 // multiplier
CYCLOPS_HIT_RADIUS :: 10.0 // px
CYCLOPS_BULLET_SPEED :: 90.0 // px/s
CYCLOPS_CROSS_DURATION :: 5.5 // s
CYCLOPS_OFFSCREEN_MARGIN :: 24.0 // px
CYCLOPS_Y_MIN :: 30.0 // px
CYCLOPS_Y_MAX :: 220.0 // px
CYCLOPS_PATTERN_COUNT :: 3 
CYCLOPS_AIMED_INTERVAL :: 0.7 // s
CYCLOPS_AIMED_BULLETS :: 5 
CYCLOPS_AIMED_FAN_DEG :: 30.0 // deg
CYCLOPS_RING_INTERVAL :: 1.3 // s
CYCLOPS_RING_BULLETS :: 10 
CYCLOPS_SPIRAL_INTERVAL :: 0.15 // s
CYCLOPS_SPIRAL_ARMS :: 2 
CYCLOPS_SPIRAL_INC_DEG :: 14.0 // deg/burst

BULLET_LIFE :: 4.0 // s
BULLET_RADIUS :: 3.0 // px
BULLET_GLOW_MULT :: 3.0 // multiplier (quad radius / bullet radius — outer halo headroom)
MAX_BULLETS :: 512

SHRINK_BOMBS_PER_LEVEL :: 3 
SHRINK_BOMB_DURATION :: 0.6 // s
SHRINK_BOMB_BURST_PARTICLES :: 24 
SHRINK_BOMB_HUD_DOT_R :: 3.0 // px
SHRINK_BOMB_HUD_DOT_GAP :: 4 // px

REFLECT_HOMING_RATE :: 1.1 // 1/s
REFLECT_DAMAGE :: 8 // hp/hit
REFLECT_IMPACT_PARTICLES :: 5 

LASER_FIRE_INTERVAL :: 0.19 // s
LASER_DAMAGE :: 7 // hp/hit
LASER_LIFETIME :: 1.0 // s
LASER_THICKNESS :: 1.0 // px
LASER_GLOW_MULT :: 4.0 // multiplier
LASER_IMPACT_PARTICLES :: 6 
LASER_BOLT_SPEED :: 900.0 // px/s
LASER_BOLT_LENGTH :: 24.0 // px

CHARGE_BEAM_BASE_DAMAGE :: 9 // hp/hit
CHARGE_BEAM_DAMAGE_BONUS :: 9 // hp/hit
CHARGE_BEAM_FULL_STAMINA_COST :: 15.0 // stamina
CHARGE_BEAM_HOLD_DELAY :: 1.0 // s
CHARGE_BEAM_RATE :: 2.0 // 1/s
CHARGE_BEAM_LIFETIME_BASE :: 0.3 // s
CHARGE_BEAM_LIFETIME_BONUS :: 0.3 // s
CHARGE_BEAM_THICKNESS_BASE :: 5.0 // px
CHARGE_BEAM_THICKNESS_BONUS :: 25.0 // px
CHARGE_BEAM_HIT_PAD :: 4.0 // px
CHARGE_BEAM_IMPACT_PARTICLES :: 6 
CHARGE_BEAM_RELEASE_BURST_BASE :: 10 
CHARGE_BEAM_RELEASE_BURST_BONUS :: 30 
CHARGE_BEAM_FRINGE_COUNT :: 15 
CHARGE_BEAM_GATHER_DIST_MIN :: 30.0 // px
CHARGE_BEAM_GATHER_DIST_RANGE :: 20.0 // px
CHARGE_BEAM_GATHER_LIFE :: 0.2 // s
MAX_BEAMS :: 16 

BEAM_BLAST_BEAM_COUNT :: 5 
BEAM_BLAST_ANGLE_STEP_DEG :: 20.0 // deg
BEAM_BLAST_DAMAGE_PER_BEAM :: 4 // hp/hit

RAPID_FIRE_INTERVAL :: 0.05 // s
RAPID_FIRE_DAMAGE :: 3 // hp/hit
RAPID_FIRE_SPEED :: 234.0 // px/s
RAPID_FIRE_LIFE :: 4.0 // s
RAPID_FIRE_RADIUS :: 1.0 // px
RAPID_FIRE_GLOW_MULT :: 3.5 // multiplier

DASH_FRENZY_MISSILES_PER_DASH :: 2 
DASH_FRENZY_LAUNCH_FAN_DEG :: 70.0 // deg
MISSILE_DAMAGE :: 8 // hp/hit
MISSILE_SPEED :: 220.0 // px/s
MISSILE_LIFE :: 2.5 // s
MISSILE_HIT_RADIUS :: 4.0 // px
MISSILE_TURN_RATE :: 6.0 // 1/s
MISSILE_INITIAL_BLIND_TIME :: 0.05 // s
MISSILE_TRAIL_LEN :: 14 
MISSILE_TRAIL_SAMPLE_INTERVAL :: 0.018 // s
MISSILE_GLOW_LAYERS :: 4 
MISSILE_BODY_RADIUS :: 2.5 // px
MISSILE_TRAIL_NODE_RADIUS :: 1.8 // px
MISSILE_IMPACT_PARTICLES :: 8 
MAX_MISSILES :: 24 

HEALTHPACK_MAX :: 8 
HEALTHPACK_DROP_CHANCE :: 0.15 
HEALTHPACK_HEAL :: 10 // hp
HEALTHPACK_RADIUS :: 6.0 // px
HEALTHPACK_ARM :: 4.5 // px
HEALTHPACK_THICK :: 3.0 // px
HEALTHPACK_PULSE_HZ :: 1.5 // Hz
HEALTHPACK_DRIFT_SPEED :: 22.0 // px/s

PARTICLE_GRAVITY :: 200.0 // px/s²
PARTICLE_SPEED_MIN :: 50.0 // px/s
PARTICLE_SPEED_MAX :: 200.0 // px/s
PARTICLE_LIFE_MIN :: 0.3 // s
PARTICLE_LIFE_MAX :: 0.7 // s
PARTICLE_SIZE_MIN :: 2.0 // px
PARTICLE_SIZE_MAX :: 6.0 // px
MAX_PARTICLES :: 256 

HP_BAR_W :: 80 // px
HP_BAR_H :: 6 // px
HP_BAR_MARGIN :: 6 // px
STATUS_BAR_GAP :: 2 // px

SCORE_KILL_LASER :: 10 // points
SCORE_KILL_CHARGE :: 15 // points
SCORE_KILL_REFLECT :: 25 // points
SCORE_KILL_RAPID :: 10 // points
SCORE_KILL_MISSILE :: 25 // points
SCORE_KILL_BOSS :: 100 // points
SCORE_FONT_SIZE :: 16 // px

VICTORY_TITLE_FONT_SIZE :: 24 // px
VICTORY_SCORE_FONT_SIZE :: 16 // px
VICTORY_PROMPT_FONT_SIZE :: 10 // px
VICTORY_OVERLAY_ALPHA :: 180 // alpha [0..255]
VICTORY_DELAY :: 2.0 // s

FINAL_VICTORY_TITLE_Y :: 30 // px
FINAL_VICTORY_LABEL_X :: 90 // px
FINAL_VICTORY_VALUE_RIGHT_X :: SCREEN_WIDTH - 90 // px
FINAL_VICTORY_BREAKDOWN_FONT_SIZE :: 12 // px
FINAL_VICTORY_LINE_GAP :: 16 // px
FINAL_VICTORY_PROMPT_BOTTOM_Y :: SCREEN_HEIGHT - 30 // px

UPGRADE_REROLLS_PER_RUN :: 1 // count

UPGRADE_TITLE_Y :: 30 // px
UPGRADE_HEADER_Y :: 100 // px
UPGRADE_HEADER_FONT_SIZE :: 14 // px
UPGRADE_CARDS_Y :: 130 // px
UPGRADE_CARD_W :: 180 // px
UPGRADE_CARD_H :: 110 // px
UPGRADE_CARD_GAP :: 24 // px
UPGRADE_NAME_FONT_SIZE :: 14 // px
UPGRADE_BODY_FONT_SIZE :: 8 // px

TRANSITION_HALF_DUR :: 0.6 // s

DIALOGUE_BOX_W :: 520 // px
DIALOGUE_BOX_H :: 72 // px
DIALOGUE_BOX_BOTTOM_MARGIN :: 14 // px
DIALOGUE_BOX_PAD :: 8 // px
DIALOGUE_ICON_SRC_W :: 8 // px
DIALOGUE_ICON_SRC_H :: 8 // px
DIALOGUE_ICON_SRC_FRAMES :: 2 
DIALOGUE_ICON_DRAW_SIZE :: 40 // px
DIALOGUE_ICON_FRAME_DUR :: 0.22 // s
DIALOGUE_NAME_FONT_SIZE :: 12 // px
DIALOGUE_TEXT_FONT_SIZE :: 12 // px
DIALOGUE_TEXT_LINE_GAP :: 3 // px
DIALOGUE_INLINE_HINT_SIZE :: 14 // px
DIALOGUE_CHAR_INTERVAL :: 0.028 // s

LEVEL2_BETWEEN_1CYC2SN_SNEAK_COUNT :: 2 
LEVEL2_BETWEEN_4SNEAKS_COUNT :: 4 
LEVEL2_BETWEEN_3CYC_TARGET :: 3 
LEVEL2_BETWEEN_3CYC_SNEAK_INTERVAL :: 4.0 // s
LEVEL2_WAVES_TO_VICTORY :: 5 

LEVEL4_GRUNT_FIRE_INTERVAL :: 1.5 // s
LEVEL4_WAVES_TO_VICTORY :: 4 

PILLAR_COUNT :: 4 
PILLAR_HP :: 50 // hp
PILLAR_FRAME_W :: 16 // px
PILLAR_FRAME_H :: 16 // px
PILLAR_FRAMES :: 4 
PILLAR_ANIM_FPS :: 6.0 // frames/s
PILLAR_DRAW_SCALE :: 2 // multiplier
PILLAR_HIT_RADIUS :: 12.0 // px
PILLAR_HIT_FLASH_TIME :: 0.08 // s
PILLAR_CORNER_MARGIN :: 36.0 // px
PILLAR_REVEAL_DUR :: 4.0 // s
PILLAR_SHUFFLE_DUR :: 1.4 // s
PILLAR_SHUFFLE_COUNT :: 2 
PILLAR_NUMBER_FONT_SIZE :: 20 // px
PILLAR_FIRE_INTERVAL :: 0.1 // s
PILLAR_BULLETS_PER_BURST :: 3 
PILLAR_ANGLE_INC_DEG :: 8.0 // deg/burst
PILLAR_BULLET_SPEED :: 75.0 // px/s
PILLAR_BLOCKED_PARTICLES :: 3 
PILLAR_KILL_SCORE :: 50 // points

MAX_LEVEL :: 5 

GUARDIAN_NAME :: "ANCIENT GUARDIAN" 
GUARDIAN_FRAME_W :: 64 // px
GUARDIAN_FRAME_H :: 64 // px
GUARDIAN_FRAMES :: 15 
GUARDIAN_ANIM_FPS :: 8.0 // frames/s
GUARDIAN_DRAW_SCALE :: 1 // multiplier
GUARDIAN_HIT_RADIUS :: 28.0 // px
GUARDIAN_HIT_FLASH_TIME :: 0.08 // s
GUARDIAN_TOTAL_HP :: 800 // hp
GUARDIAN_SPAWN_X :: 320.0 // px
GUARDIAN_SPAWN_Y :: 90.0 // px
GUARDIAN_SWAY_AMP :: 60.0 // px
GUARDIAN_SWAY_FREQ :: 0.25 // Hz

GUARDIAN_ORB_COUNT :: 6 
GUARDIAN_ORB_HP :: 150 // hp
GUARDIAN_ORB_RADIUS :: 24.0 // px
GUARDIAN_ORB_HIT_RADIUS :: 24.0 // px
GUARDIAN_ORB_ORBIT_RADIUS :: 92.0 // px
GUARDIAN_ORB_ORBIT_SPEED :: 0.55 // rad/s
GUARDIAN_ORB_FIRE_INTERVAL :: 0.18 // s
GUARDIAN_ORB_BULLETS_PER_BURST :: 2 
GUARDIAN_ORB_ANGLE_INC_DEG :: 11.0 // deg/burst
GUARDIAN_ORB_BULLET_SPEED :: 70.0 // px/s
GUARDIAN_ORB_VULNERABLE_TIME :: 7.0 // s
GUARDIAN_ORB_RESPAWN_HP :: 150 // hp
GUARDIAN_WINDOW_DURATION :: 12.0 // s
GUARDIAN_ORB_KILL_SCORE :: 75 // points

GUARDIAN_FIRE_INTERVAL :: 0.3 // s
GUARDIAN_RING_BULLETS :: 32 
GUARDIAN_BULLET_SPEED :: 95.0 // px/s

PAUSE_OVERLAY_ALPHA :: 200 // alpha [0..255]
PAUSE_TITLE_FONT_SIZE :: 20 // px
PAUSE_TITLE_Y :: 50 // px
PAUSE_MENU_TOP_Y :: 130 // px
PAUSE_ITEM_FONT_SIZE :: 14 // px
PAUSE_ITEM_GAP :: 14 // px
PAUSE_BODY_FONT_SIZE :: 10 // px
PAUSE_BODY_LINE_GAP :: 18 // px
PAUSE_SLIDER_W :: 160 // px
PAUSE_SLIDER_H :: 6 // px
PAUSE_VOLUME_STEP :: 0.05 // multiplier

MAIN_MENU_OVERLAY_ALPHA :: 110 // alpha [0..255]
MAIN_MENU_TITLE_FONT_SIZE :: 36 // px
MAIN_MENU_TITLE_Y :: 70 // px
MAIN_MENU_ITEMS_TOP_Y :: 170 // px

MISSION_TITLE_FONT_SIZE :: 28 // px
MISSION_SUBTITLE_FONT_SIZE :: 12 // px
MISSION_TITLE_Y :: 84 // px
MISSION_SUBTITLE_GAP :: 10 // px
MISSION_TITLE_FADE_IN :: 0.5 // s
MISSION_TITLE_HOLD :: 2.0 // s
MISSION_TITLE_FADE_OUT :: 0.7 // s

HINT_ICON_SIZE :: 16 // px
HINT_ICON_GAP :: 2 // px
HINT_TEXT_GAP :: 4 // px
